### ISSUE TITLE
[Question] missing .dll for debug version

### ISSUE THREAD

**Issue by sixsik6** [Ty-Matthews-VisualStudio/Wally#4]
Not sure if I'm being stupid, but following the readme and placing the WallyD_157.exe in the same directory as Wally.exe results in the program not opening. System error of **mfc140d.dll** and **VCRUNTIME140D.dll** are both not found. Reinstalled several times and no dice.

**Comment by ty-matthews** [comment]
Those are the debug versions of the VC runtime, which I believe only come with Visual Studio.  I'm not allowed to redistribute them.  So if you're trying to run the Wally_D version, you'll need to have Visual Studio installed.  I believe there is a way to just install the build tools with Visual Studio, which will make the install much shorter.  Take a look at this SO post: https://stackoverflow.com/a/58018577

I should probably just build a release version and post that in the Binaries folder...
