### ISSUE TITLE
Consider distributing binaries differently

### ISSUE THREAD

**Issue by res2k** [Ty-Matthews-VisualStudio/Wally#6]
Hi,
currently, binaries are distributed as files in the "Binaries" subfolder, but git isn't that great for such things. (For one, those are relatively large files which are now contained in the git history - ie when cloning, they'll be carried along, even obsolete copies.)
Hence, I'd like to request that you look into alternative ways of distributing binaries - for example, GitHub itself has the "Releases" feature.

**Comment by ty-matthews** [comment]
Done, deleted the Binaries folder entirely and published the most recent development version (157) to the Releases section.
